/** Keys must match API <c>SchoolThemePreset</c> ids. */
export const SCHOOL_THEME_IDS = [
  'default',
  'ocean',
  'forest',
  'sunset',
  'violet',
  'rose'
] as const;

export type SchoolThemeId = (typeof SCHOOL_THEME_IDS)[number];

const PRESETS: Record<SchoolThemeId, Record<string, string>> = {
  default: {
    '--app-primary': '#2563eb',
    '--app-primary-hover': '#1d4ed8',
    '--app-secondary': '#0f766e',
    '--app-secondary-hover': '#115e59',
    '--app-surface': '#ffffff',
    '--app-bg': '#f8fafc',
    '--app-text': '#0f172a',
    '--app-text-muted': '#64748b',
    '--app-label': '#334155',
    '--app-border': '#e2e8f0',
    '--app-input-border': '#cbd5e1',
    '--app-danger': '#b91c1c',
    '--app-slot-muted': '#f8fafc',
    '--app-slot-border': '#e2e8f0',
    '--app-nav-active-bg': '#e0f2fe',
    '--app-nav-active-fg': '#075985',
    '--app-nav-link': '#475569',
    '--app-shell-text': '#334155',
    '--app-link': '#2563eb',
    '--login-gradient-start': '#eef2ff',
    '--login-gradient-mid': '#f8fafc',
    '--login-gradient-end': '#ecfdf5',
    '--login-accent': '#5b4ddb',
    '--login-accent-mid': '#4338ca',
    '--login-accent-deep': '#3730a3',
    '--login-card': '#ffffff',
    '--login-text': '#0f172a',
    '--login-muted': '#64748b',
    '--login-input-bg': '#f1f5f9',
    '--login-icon': '#94a3b8',
    '--login-forgot': '#c2410c',
    '--login-google-border': '#e2e8f0'
  },
  ocean: {
    '--app-primary': '#0d9488',
    '--app-primary-hover': '#0f766e',
    '--app-secondary': '#0891b2',
    '--app-secondary-hover': '#0e7490',
    '--app-surface': '#ffffff',
    '--app-bg': '#f0fdfa',
    '--app-text': '#0f172a',
    '--app-text-muted': '#5b7c78',
    '--app-label': '#134e4a',
    '--app-border': '#ccfbf1',
    '--app-input-border': '#99f6e4',
    '--app-danger': '#be123c',
    '--app-slot-muted': '#ecfeff',
    '--app-slot-border': '#a5f3fc',
    '--app-nav-active-bg': '#cffafe',
    '--app-nav-active-fg': '#155e75',
    '--app-nav-link': '#476969',
    '--app-shell-text': '#115e59',
    '--app-link': '#0d9488',
    '--login-gradient-start': '#ecfeff',
    '--login-gradient-mid': '#f0fdfa',
    '--login-gradient-end': '#e0f2fe',
    '--login-accent': '#0d9488',
    '--login-accent-mid': '#0f766e',
    '--login-accent-deep': '#115e59',
    '--login-card': '#ffffff',
    '--login-text': '#0f172a',
    '--login-muted': '#5b7c78',
    '--login-input-bg': '#ecfeff',
    '--login-icon': '#94a3b8',
    '--login-forgot': '#0e7490',
    '--login-google-border': '#99f6e4'
  },
  forest: {
    '--app-primary': '#059669',
    '--app-primary-hover': '#047857',
    '--app-secondary': '#65a30d',
    '--app-secondary-hover': '#4d7c0f',
    '--app-surface': '#ffffff',
    '--app-bg': '#f7fee7',
    '--app-text': '#14532d',
    '--app-text-muted': '#4d7c0f',
    '--app-label': '#365314',
    '--app-border': '#d9f99d',
    '--app-input-border': '#bef264',
    '--app-danger': '#b91c1c',
    '--app-slot-muted': '#ecfccb',
    '--app-slot-border': '#d9f99d',
    '--app-nav-active-bg': '#dcfce7',
    '--app-nav-active-fg': '#166534',
    '--app-nav-link': '#3f6212',
    '--app-shell-text': '#365314',
    '--app-link': '#059669',
    '--login-gradient-start': '#ecfccb',
    '--login-gradient-mid': '#f7fee7',
    '--login-gradient-end': '#d1fae5',
    '--login-accent': '#059669',
    '--login-accent-mid': '#047857',
    '--login-accent-deep': '#065f46',
    '--login-card': '#ffffff',
    '--login-text': '#14532d',
    '--login-muted': '#4d7c0f',
    '--login-input-bg': '#ecfccb',
    '--login-icon': '#84cc16',
    '--login-forgot': '#a16207',
    '--login-google-border': '#bef264'
  },
  sunset: {
    '--app-primary': '#ea580c',
    '--app-primary-hover': '#c2410c',
    '--app-secondary': '#ca8a04',
    '--app-secondary-hover': '#a16207',
    '--app-surface': '#ffffff',
    '--app-bg': '#fff7ed',
    '--app-text': '#431407',
    '--app-text-muted': '#9a3412',
    '--app-label': '#7c2d12',
    '--app-border': '#fed7aa',
    '--app-input-border': '#fdba74',
    '--app-danger': '#b91c1c',
    '--app-slot-muted': '#ffedd5',
    '--app-slot-border': '#fed7aa',
    '--app-nav-active-bg': '#ffedd5',
    '--app-nav-active-fg': '#9a3412',
    '--app-nav-link': '#9a3412',
    '--app-shell-text': '#7c2d12',
    '--app-link': '#ea580c',
    '--login-gradient-start': '#ffedd5',
    '--login-gradient-mid': '#fff7ed',
    '--login-gradient-end': '#fef3c7',
    '--login-accent': '#ea580c',
    '--login-accent-mid': '#c2410c',
    '--login-accent-deep': '#9a3412',
    '--login-card': '#ffffff',
    '--login-text': '#431407',
    '--login-muted': '#9a3412',
    '--login-input-bg': '#ffedd5',
    '--login-icon': '#fb923c',
    '--login-forgot': '#b45309',
    '--login-google-border': '#fdba74'
  },
  violet: {
    '--app-primary': '#7c3aed',
    '--app-primary-hover': '#6d28d9',
    '--app-secondary': '#6366f1',
    '--app-secondary-hover': '#4f46e5',
    '--app-surface': '#ffffff',
    '--app-bg': '#f5f3ff',
    '--app-text': '#1e1b4b',
    '--app-text-muted': '#5b21b6',
    '--app-label': '#4c1d95',
    '--app-border': '#ddd6fe',
    '--app-input-border': '#c4b5fd',
    '--app-danger': '#be123c',
    '--app-slot-muted': '#ede9fe',
    '--app-slot-border': '#ddd6fe',
    '--app-nav-active-bg': '#ede9fe',
    '--app-nav-active-fg': '#5b21b6',
    '--app-nav-link': '#6d28d9',
    '--app-shell-text': '#4c1d95',
    '--app-link': '#7c3aed',
    '--login-gradient-start': '#ede9fe',
    '--login-gradient-mid': '#f5f3ff',
    '--login-gradient-end': '#e0e7ff',
    '--login-accent': '#7c3aed',
    '--login-accent-mid': '#6d28d9',
    '--login-accent-deep': '#5b21b6',
    '--login-card': '#ffffff',
    '--login-text': '#1e1b4b',
    '--login-muted': '#5b21b6',
    '--login-input-bg': '#ede9fe',
    '--login-icon': '#a78bfa',
    '--login-forgot': '#7c3aed',
    '--login-google-border': '#c4b5fd'
  },
  rose: {
    '--app-primary': '#e11d48',
    '--app-primary-hover': '#be123c',
    '--app-secondary': '#db2777',
    '--app-secondary-hover': '#be185d',
    '--app-surface': '#ffffff',
    '--app-bg': '#fff1f2',
    '--app-text': '#4c0519',
    '--app-text-muted': '#9f1239',
    '--app-label': '#881337',
    '--app-border': '#fecdd3',
    '--app-input-border': '#fda4af',
    '--app-danger': '#991b1b',
    '--app-slot-muted': '#ffe4e6',
    '--app-slot-border': '#fecdd3',
    '--app-nav-active-bg': '#ffe4e6',
    '--app-nav-active-fg': '#9f1239',
    '--app-nav-link': '#be123c',
    '--app-shell-text': '#881337',
    '--app-link': '#e11d48',
    '--login-gradient-start': '#ffe4e6',
    '--login-gradient-mid': '#fff1f2',
    '--login-gradient-end': '#fce7f3',
    '--login-accent': '#e11d48',
    '--login-accent-mid': '#be123c',
    '--login-accent-deep': '#9f1239',
    '--login-card': '#ffffff',
    '--login-text': '#4c0519',
    '--login-muted': '#9f1239',
    '--login-input-bg': '#ffe4e6',
    '--login-icon': '#fb7185',
    '--login-forgot': '#be123c',
    '--login-google-border': '#fda4af'
  }
};

export function applySchoolTheme(presetId: string | undefined | null): void {
  const id = (presetId && presetId in PRESETS ? presetId : 'default') as SchoolThemeId;
  const vars = PRESETS[id];
  const root = document.documentElement;
  for (const [key, value] of Object.entries(vars)) {
    root.style.setProperty(key, value);
  }
}
